// IBM Bob tab — live MCP-grounded assistant with runtime provenance.
import { useEffect, useRef, useState } from "react";
import { Send, Cpu, Zap, MessageSquare, HelpCircle } from "lucide-react";
import { api } from "../lib/api";

type Msg = { role: string; content: string; actions?: string[]; mode?: string; provider?: string };
type BobStatus = { provider: string; configured: boolean; cli_available: boolean; mcp: string; tools: number; fallback: string };
const QUICK_PROMPTS = ["What is the 72-hour congestion outlook and which terminal is the biggest risk?", "Why is the current hotspot constrained, and what should the operator do next?", "Compare CP-SAT against FIFO and explain the operational gain.", "Simulate a 25% crane-capacity outage. What changes and what should we do?", "Which vessels should divert or slow-steam, and what savings are expected?", "Prepare the next 6-hour shift handover with the top actions."];
function ModeChip({ mode, provider }: { mode?: string; provider?: string }) { if (!mode && !provider) return null; const live = provider === "bob"; return <span className="inline-flex items-center gap-0.5 px-1.5 py-0.5 rounded text-[9px] font-mono border" style={{ color: live ? "var(--accent)" : "var(--text-muted)", borderColor: live ? "var(--accent)" : "var(--border-subtle)", background: live ? `var(--accent)18` : "transparent" }}><Cpu className="w-2.5 h-2.5" />{live ? "IBM Bob" : "Engine fallback"}</span>; }
function ActionChips({ actions }: { actions?: string[] }) { if (!actions?.length) return null; return <div className="flex flex-wrap gap-1 mt-1.5">{actions.map((a, i) => <span key={`${a}-${i}`} className="inline-flex items-center gap-0.5 px-1.5 py-0.5 rounded text-[9px] font-mono bg-[var(--bg-surface)] border border-[var(--border-subtle)] text-[var(--brand)]"><Zap className="w-2.5 h-2.5" />{a}</span>)}</div>; }
function TypingIndicator() { return <div className="flex items-center gap-1.5 px-3 py-2 rounded-lg bg-[var(--bg-surface-elevated)] border border-[var(--border-subtle)] w-fit"><Cpu className="w-3.5 h-3.5 text-[var(--brand)] animate-spin" /><span className="text-xs text-[var(--text-muted)]">Bob is querying port engines via MCP…</span></div>; }
export default function Bob() {
  const [msgs, setMsgs] = useState<Msg[]>([]); const [text, setText] = useState(""); const [busy, setBusy] = useState(false); const [status, setStatus] = useState<BobStatus | null>(null);
  const endRef = useRef<HTMLDivElement>(null); const inputRef = useRef<HTMLInputElement>(null);
  useEffect(() => { api.bobStatus().then(setStatus).catch(() => setStatus(null)); }, []);
  useEffect(() => { endRef.current?.scrollIntoView({ behavior: "smooth" }); }, [msgs, busy]);
  async function send(q?: string) { const message = (q ?? text).trim(); if (!message || busy) return; setMsgs((m) => [...m, { role: "user", content: message }]); setText(""); setBusy(true); try { const r = await api.bob(message); setMsgs((m) => [...m, { role: "assistant", content: r.content, actions: r.actions, mode: r.mode, provider: r.provider }]); setStatus((s) => s ? { ...s, provider: r.provider } : s); } catch (e) { setMsgs((m) => [...m, { role: "assistant", content: `⚠ Engine error: ${e}` }]); } finally { setBusy(false); setTimeout(() => inputRef.current?.focus(), 50); } }
  function handleKeyDown(e: React.KeyboardEvent) { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); send(); } }
  const live = status?.provider === "bob" && status.configured && status.cli_available;
  const toolCount = status?.tools ?? 12;
  return <div className="grid lg:grid-cols-[1fr_260px] gap-4 h-full">
    <div className="flex flex-col rounded-lg border border-[var(--border-default)] bg-[var(--bg-surface)] overflow-hidden">
      <div className="flex items-center justify-between px-4 py-2.5 border-b border-[var(--border-subtle)] bg-[var(--bg-surface-elevated)]"><div className="flex items-center gap-2"><MessageSquare className="w-4 h-4 text-[var(--brand)]" /><span className="font-semibold text-sm">Bob — Operations Intelligence</span></div><div className="flex items-center gap-1.5 text-[10px] font-mono text-[var(--text-muted)]"><span className={`w-1.5 h-1.5 rounded-full ${live ? "bg-[var(--status-success)]" : "bg-[var(--status-warning)]"}`} />{live ? `IBM Bob · MCP · ${toolCount} tools live` : "IBM Bob unavailable · engine fallback"}</div></div>
      <div className="flex-1 overflow-y-auto p-4 space-y-3" style={{ maxHeight: "55vh" }}>{!msgs.length && <div className="text-sm text-[var(--text-muted)] space-y-2"><div className="flex items-center gap-2"><HelpCircle className="w-4 h-4 text-[var(--brand)] shrink-0" /><span>Ask an operational question. Bob calls the relevant MCP tools and explains the decision from their outputs.</span></div><p className="text-xs">Tool chips below each answer are the actual actions returned by the Bob process.</p></div>}{msgs.map((m, i) => <div key={i} className={`flex flex-col ${m.role === "user" ? "items-end" : "items-start"}`}><div className={`max-w-[85%] px-3 py-2 rounded-lg text-sm ${m.role === "user" ? "bg-[var(--brand-soft)] border border-[var(--brand-border)] ml-8" : "bg-[var(--bg-surface-elevated)] border border-[var(--border-subtle)] mr-8"}`}><div className="flex items-center gap-1.5 mb-1"><span className="text-[10px] font-bold text-[var(--text-muted)] uppercase">{m.role}</span><ModeChip mode={m.mode} provider={m.provider} /></div><div className="whitespace-pre-wrap leading-relaxed">{m.content}</div><ActionChips actions={m.actions} /></div></div>)}{busy && <div className="flex items-start"><TypingIndicator /></div>}<div ref={endRef} /></div>
      <div className="px-4 py-3 border-t border-[var(--border-subtle)] bg-[var(--bg-surface-elevated)]"><div className="flex items-center gap-2"><input ref={inputRef} value={text} onChange={(e) => setText(e.target.value)} onKeyDown={handleKeyDown} placeholder="Ask Bob about congestion, optimisation, routing, or scenarios…" disabled={busy} className="flex-1 min-w-0 px-3 py-2 rounded-md text-sm bg-[var(--bg-surface)] border border-[var(--border-default)] text-[var(--text-primary)] placeholder-[var(--text-muted)] focus:outline-none focus:border-[var(--brand)] disabled:opacity-50 transition-colors" /><button onClick={() => send()} disabled={busy || !text.trim()} aria-label="Send message" className="flex items-center justify-center w-9 h-9 rounded-md bg-[var(--brand)] hover:bg-[var(--brand-hover)] text-white transition-colors cursor-pointer disabled:opacity-40 disabled:cursor-not-allowed shrink-0"><Send className="w-4 h-4" /></button></div><div className="text-[9px] text-[var(--text-muted)] mt-1.5 font-mono">Enter to send · Shift+Enter for newline</div></div>
    </div>
    <div className="flex flex-col rounded-lg border border-[var(--border-default)] bg-[var(--bg-surface)] overflow-hidden"><div className="px-4 py-2.5 border-b border-[var(--border-subtle)] bg-[var(--bg-surface-elevated)]"><span className="font-semibold text-sm">Operator prompts</span></div><div className="flex-1 overflow-y-auto p-3 space-y-2">{QUICK_PROMPTS.map((q) => <button key={q} onClick={() => send(q)} disabled={busy} className="w-full text-left text-xs px-3 py-2.5 rounded-md border border-[var(--border-subtle)] bg-[var(--bg-surface-elevated)] hover:border-[var(--brand)] hover:bg-[var(--brand-soft)] transition-all cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed text-[var(--text-secondary)]">{q}</button>)}</div><div className="px-4 py-2.5 border-t border-[var(--border-subtle)]"><div className="text-[9px] text-[var(--text-muted)] font-mono">PortFlow SBX · MCP · {toolCount} tools · IBM Bob first</div></div></div>
  </div>;
}
